dependencies:
  - python
  - numpy
  - pandas
  - arxiv
  - asttokens
  - certifi
  - charset-normalizer
  - contourpy
  - cycler
  - decorator
  - exceptiongroup
  - executing
  - feedparser
  - fonttools
  - idna
  - ipython
  - isodate
  - jedi
  - jinja2
  - jsonpickle
  - kiwisolver
  - matplotlib
  - matplotlib-inline
  - mnemonic
  - networkx
  - packaging
  - parso
  - pexpect
  - pillow
  - prompt-toolkit
  - ptyprocess
  - pygments
  - pyparsing
  - python-dateutil
  - pytz
  - pyvis
  - rdflib
  - requests
  - scipy
  - setuptools
  - sgmllib3k
  - six
  - tqdm
  - traitlets
  - typing-extensions
  - tzdata
  - urllib3
  - wcwidth
  - wget
  - wheel
  - utils